name: ci on ubuntu

on:
  push:
    branches:
      - master
      - espnet3
  pull_request:
    branches:
      - master
      - espnet3

jobs:
  process_labels:
    runs-on: ubuntu-latest
    outputs:
      is_docker: ${{ steps.step1.outputs.is_docker }}
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.9
      - name: Check whether PR is related to only docker
        id: step1
        run: |
          if [ -z "$GITHUB_PR_LABEL_ESPNET2" ] && [ -z "$GITHUB_PR_LABEL_ESPNET3" ] && [ -n "$GITHUB_PR_LABEL_DOCKER" ]; then
            echo "is_docker=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_docker=false" >> "$GITHUB_OUTPUT"
          fi

  setup_environment:
    runs-on: ubuntu-latest
    needs: process_labels
    if: |
      github.event.pull_request.draft == false
    strategy:
      max-parallel: 20
      matrix:
        python-version: ["3.10", "3.12"]
        pytorch-version: [2.5.1, 2.7.1, 2.8.0, 2.9.1]
        chainer-version: [6.0.0]
        use-conda: [false]
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v5
        id: cache-venv
        with:
          path: |
            ~/.cache/pip
            tools
          key: ${{ runner.os }}-venv-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/Makefile') }}
      - name: Make environment
        if: steps.cache-venv.outputs.cache-hit != 'true'
        uses: ./.github/actions/prepare-environment
        with:
          os-version: ubuntu
          python-version: ${{ matrix.python-version }}
          pytorch-version: ${{ matrix.pytorch-version }}
          chainer-version: ${{ matrix.chainer-version }}
          use-conda: ${{ matrix.use-conda }}
      - name: Install Kaldi
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: ./ci/install_kaldi.sh

  test_python_espnet2:
    runs-on: ubuntu-latest
    needs: setup_environment
    if: |
      github.event.pull_request.draft == false
    strategy:
      max-parallel: 20
      matrix:
        python-version: ["3.10", "3.12"]
        pytorch-version: [2.5.1, 2.7.1, 2.8.0, 2.9.1]
        use-conda: [false]
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/pip
            tools
          key: ${{ runner.os }}-venv-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/Makefile') }}
      - name: Install System Dependencies
        run: |
            sudo apt-get update -qq
            sudo apt-get install -qq -y cmake libsndfile1-dev bc sox ffmpeg libjpeg-dev
      - name: test python
        run: ./ci/test_python_espnet2.sh
      - uses: codecov/codecov-action@v5
        with:
          flags: test_python_espnet2
      - name: coverage erase
        continue-on-error: true
        run: |
          source tools/activate_python.sh
          coverage erase

  test_utils_espnet2:
    runs-on: ubuntu-latest
    needs: setup_environment
    if: |
      github.event.pull_request.draft == false
    strategy:
      max-parallel: 20
      matrix:
        python-version: ["3.10", "3.12"]
        pytorch-version: [2.7.1]
        use-conda: [false]
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/pip
            tools
          key: ${{ runner.os }}-venv-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/Makefile') }}
      - name: Install System Dependencies
        run: |
            sudo apt-get update -qq
            sudo apt-get install -qq -y cmake libsndfile1-dev bc sox ffmpeg libjpeg-dev
      - name: test utils
        run: ./ci/test_utils.sh
      - uses: codecov/codecov-action@v5
        with:
          flags: test_utils
      - name: coverage erase
        continue-on-error: true
        run: |
          source tools/activate_python.sh
          coverage erase

  test_shell_espnet2:
    runs-on: ubuntu-latest
    needs: setup_environment
    if: |
      github.event.pull_request.draft == false
    strategy:
      max-parallel: 20
      matrix:
        python-version: ["3.10"]
        pytorch-version: [2.7.1]
        use-conda: [false]
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/pip
            tools
          key: ${{ runner.os }}-venv-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/Makefile') }}
      - name: Install System Dependencies
        run: |
            sudo apt-get update -qq
            sudo apt-get install -qq -y cmake libsndfile1-dev bc sox ffmpeg libjpeg-dev
      - name: test shell
        run: |
          ./ci/test_shell_espnet2.sh

  test_integration_espnet2:
    runs-on: ubuntu-latest
    needs: setup_environment
    if: |
      github.event.pull_request.draft == false
    strategy:
      max-parallel: 20
      matrix:
        python-version: ["3.10", "3.12"]
        pytorch-version: [2.5.1, 2.9.1]
        use-conda: [false]
        exclude:
            - python-version: "3.12"
              pytorch-version: 2.5.1
              use-conda: false
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/pip
            tools
          key: ${{ runner.os }}-venv-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/Makefile') }}
      - name: Install System Dependencies
        run: |
            sudo apt-get update -qq
            sudo apt-get install -qq -y cmake libsndfile1-dev bc sox ffmpeg
      - name: test espnet2 integration
        run: ./ci/test_integration_espnet2.sh
      - uses: codecov/codecov-action@v5
        with:
          flags: test_integration_espnet2

  test_configuration_espnet2:
    runs-on: ubuntu-latest
    needs: setup_environment
    if: |
      github.event.pull_request.draft == false
    strategy:
      max-parallel: 20
      matrix:
        python-version: ["3.10"]
        pytorch-version: ["2.7.1"]
        use-conda: [false]
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/pip
            tools
          key: ${{ runner.os }}-venv-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/Makefile') }}
      - name: Install System Dependencies
        run: |
            sudo apt-get update -qq
            sudo apt-get install -qq -y cmake libsndfile1-dev bc sox ffmpeg
      - name: test configuration
        run: ./ci/test_configuration_espnet2.sh
      - uses: codecov/codecov-action@v5
        with:
          flags: test_configuration_espnet2

  test_python_espnet3:
    runs-on: ubuntu-latest
    needs: setup_environment
    if: |
      github.event.pull_request.draft == false
    strategy:
      max-parallel: 20
      matrix:
        python-version: ["3.10", "3.12"]
        pytorch-version: [2.5.1, 2.7.1, 2.8.0, 2.9.1]
        chainer-version: [6.0.0]
        use-conda: [false]
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/pip
            tools
          key: ${{ runner.os }}-venv-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/Makefile') }}
      - name: Install System Dependencies
        run: |
            sudo apt-get update -qq
            sudo apt-get install -qq -y cmake libsndfile1-dev bc sox ffmpeg libjpeg-dev
      - name: test python
        run: ./ci/test_python_espnet3.sh
      - uses: codecov/codecov-action@v5
        with:
          flags: test_python_espnet3
      - name: coverage erase
        continue-on-error: true
        run: |
          source tools/activate_python.sh
          coverage erase

  test_import:
    runs-on: ubuntu-latest
    needs: process_labels
    if: |
      github.event.pull_request.draft == false
    strategy:
      max-parallel: 20
      matrix:
        python-version: ["3.10"]
        pytorch-version: [2.7.1]
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install -qq -y libsndfile1-dev
        python3 -m pip install --upgrade pip setuptools wheel
    - name: Install espnet with the least requirement
      env:
        TH_VERSION: ${{ matrix.pytorch-version }}
      run: |
        python3 -m pip install -U "Cython<3.1.0"
        python3 -m pip install -U numba six
        python3 -m pip install build
        ./tools/installers/install_torch.sh false ${TH_VERSION} CPU
        python3 -m build --wheel
        python3 -m pip install "$(echo dist/espnet-*.whl)"[all]
        # log
        python3 -m pip freeze
    - name: Import all modules (Try1)
      run: |
        python3 ./ci/test_import_all.py
    - name: Install espnet with the full requirement
      env:
        TH_VERSION: ${{ matrix.pytorch-version }}
      run: |
        python3 -m pip install "$(ls dist/espnet-*.whl)[all]"
        # log
        python3 -m pip freeze
    - name: Import all modules (Try2)
      run: |
        python3 -q -X faulthandler ./ci/test_import_all.py

  check_kaldi_symlinks:
    runs-on: ubuntu-latest
    needs: process_labels
    if: |
      github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@master
    - run: ci/check_kaldi_symlinks.sh
