name: publish docker image

on:
  schedule:
    # Runs every Monday at midnight UTC
    - cron: "0 0 * * 1"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    environment: docker
    # Only runs if the current branch is 'master'
    # Only runs if the current repository is espnet/espnet
    if: github.repository == 'espnet/espnet' && github.ref == 'refs/heads/master'
    strategy:
      matrix:
        include:
          - variant: cpu
            from_tag: runtime-latest
            image_tag: espnet/espnet:cpu-latest
            cuda_arg: ""
          - variant: gpu
            from_tag: cuda-latest
            image_tag: espnet/espnet:gpu-latest
            cuda_arg: "--build-arg CUDA_VER=11.1"
    steps:
      - uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.variant }} container
        run: |
          cd docker
          docker build --build-arg FROM_TAG=${{ matrix.from_tag }} \
            ${{ matrix.cuda_arg }} \
            -f prebuilt/devel.dockerfile \
            --target devel \
            -t ${{ matrix.image_tag }} .
          docker push ${{ matrix.image_tag }}
